{"name": "Проверка создания заказа c неверным хешем ингредиента", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture()\n    def login_user():\n        user_body = GeneratePayload.generate_user_payload()\n        new_user = UserMethods.create_new_user(user_body)\n        email = user_body['email']\n        password = user_body['password']\n        response = new_user[0].json()\n>       access_token = response['accessToken']\nE       KeyError: 'accessToken'\n\ntests\\conftest.py:28: KeyError"}, "start": 1747143200156, "stop": 1747143200156, "uuid": "4c65bec1-2e9c-478a-8b11-068ea2b61536", "historyId": "03c79d19226ef3ef96e53c670199dbe3", "testCaseId": "03c79d19226ef3ef96e53c670199dbe3", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_without_ingredients", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-B0AK6U5"}, {"name": "thread", "value": "4380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}